import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../features/auth/AuthProvider';
import { AuthLayout } from './LoginPage';
const schema = z.object({ fullName: z.string().trim().min(2, 'Enter your full name.').max(120), email: z.string().email('Enter a valid email address.'), password: z.string().min(12, 'Use at least 12 characters.').max(128), confirmPassword: z.string(), rememberMe: z.boolean() }).refine(value => value.password === value.confirmPassword, { message: 'Passwords do not match.', path: ['confirmPassword'] });
type FormValues = z.infer<typeof schema>;
export function RegisterPage() { const { register: registerAccount } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { rememberMe: true } }); const submit = async (values: FormValues) => { setError(''); try { await registerAccount(values); navigate('/', { replace: true }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Registration failed.'); } }; return <AuthLayout title="Create your buyer account" subtitle="Start your verified procurement workspace."><form onSubmit={handleSubmit(submit)} noValidate><Field label="Full name" error={errors.fullName?.message}><input autoComplete="name" {...register('fullName')} placeholder="Your name" /></Field><Field label="Work email" error={errors.email?.message}><input autoComplete="email" {...register('email')} placeholder="you@company.com" /></Field><Field label="Password" error={errors.password?.message}><input autoComplete="new-password" type="password" {...register('password')} placeholder="12 or more characters" /></Field><Field label="Confirm password" error={errors.confirmPassword?.message}><input autoComplete="new-password" type="password" {...register('confirmPassword')} placeholder="Repeat your password" /></Field><label className="check"><input type="checkbox" {...register('rememberMe')} /> Keep me signed in on this device</label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={isSubmitting}>{isSubmitting ? 'Creating account…' : 'Create account'} <ArrowRight size={16}/></button></form><p className="auth-footer">Already have an account? <Link to="/login">Sign in</Link></p></AuthLayout>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small>{error}</small>}</label>; }
