import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowRight } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useSearchParams } from 'react-router-dom';
import { z } from 'zod';
import { AuthLayout } from './LoginPage';
const schema = z.object({ password: z.string().min(12, 'Use at least 12 characters.'), confirmPassword: z.string() }).refine(value => value.password === value.confirmPassword, { message: 'Passwords do not match.', path: ['confirmPassword'] });
type Values = z.infer<typeof schema>;
export function ResetPasswordPage() { const [params] = useSearchParams(); const [error, setError] = useState(''); const [complete, setComplete] = useState(false); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema) }); const submit = async (values: Values) => { const token = params.get('token'); if (!token) { setError('This password reset link is invalid.'); return; } setError(''); try { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:8080/api/v1'}/auth/reset-password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...values, token }) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? 'Unable to reset password.'); setComplete(true); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to reset password.'); } }; return <AuthLayout title="Choose a new password" subtitle="Use a unique password with at least 12 characters.">{complete ? <div className="auth-success"><h2>Password updated</h2><p>You can now sign in using your new password.</p><Link className="primary auth-submit" to="/login">Continue to sign in</Link></div> : <form onSubmit={handleSubmit(submit)} noValidate><Field label="New password" error={errors.password?.message}><input autoComplete="new-password" type="password" {...register('password')} /></Field><Field label="Confirm new password" error={errors.confirmPassword?.message}><input autoComplete="new-password" type="password" {...register('confirmPassword')} /></Field>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary auth-submit" disabled={isSubmitting}>{isSubmitting ? 'Updating…' : 'Update password'} <ArrowRight size={16}/></button></form>}</AuthLayout>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small>{error}</small>}</label>; }
