import { createRoot } from 'react-dom/client';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { AuthProvider } from './features/auth/AuthProvider';
import { ProtectedRoute } from './features/auth/ProtectedRoute';
import { AdminSessionPage } from './pages/AdminSessionPage';
import { BuyerDashboardPage } from './pages/BuyerDashboardPage';
import { BuyerRegistrationPage } from './pages/BuyerRegistrationPage';
import { ForgotPasswordPage } from './pages/ForgotPasswordPage';
import { LoginPage } from './pages/LoginPage';
import { RegisterPage } from './pages/RegisterPage';
import { ResetPasswordPage } from './pages/ResetPasswordPage';
import { VerifyEmailPage } from './pages/VerifyEmailPage';
import './styles.css';
import './auth.css';
createRoot(document.getElementById('root')!).render(<AuthProvider><BrowserRouter><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/forgot-password" element={<ForgotPasswordPage/>}/><Route path="/reset-password" element={<ResetPasswordPage/>}/><Route path="/verify-email" element={<VerifyEmailPage/>}/><Route element={<ProtectedRoute roles={['BUYER']}/>}><Route path="/" element={<BuyerDashboardPage/>}/><Route path="/buyer/registration" element={<BuyerRegistrationPage/>}/></Route><Route element={<ProtectedRoute roles={['ADMIN']}/>}><Route path="/admin" element={<AdminSessionPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter></AuthProvider>);
